"""
src/renderers/markdown.py
=========================
Renders a Briefing to GitHub-Flavored Markdown.

Output structure:
  # News Radar — YYYY-MM-DD

  > Executive summary paragraph

  ## Top Topics
  `AI` `Python` `open source`

  ---

  ## 1. Story Headline  [score: 9/10]
  **Source:** Hacker News | **Published:** 2026-06-21 10:00 UTC
  **[Read →](https://example.com/article)**
  | [Comments](https://news.ycombinator.com/...)

  ### Summary
  Para 1...

  Para 2...

  Para 3...

  ### Key Points
  - Point 1
  - Point 2
  - Point 3

  ---
  (repeated for each item)

  ---
  *Generated by News Radar · gpt-4o-mini · 2026-06-21 15:00 UTC*

Design:
  - Pure Python string building (no Jinja2 dependency for markdown)
  - All strings are sanitized for Markdown compatibility
  - Score badges use emoji for visual clarity in GitHub rendering
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from src.models import Briefing, SummarizedItem

# ---------------------------------------------------------------------------
# Score → badge emoji
# ---------------------------------------------------------------------------

_SCORE_EMOJI = {
    10: "🔥",
    9: "⭐",
    8: "✅",
    7: "👍",
    6: "➡️",
    5: "⚖️",
    4: "👀",
    3: "⬇️",
    2: "❌",
    1: "💀",
}


def _score_badge(score: int) -> str:
    emoji = _SCORE_EMOJI.get(score, "•")
    return f"{emoji} {score}/10"


def _md_escape(text: str) -> str:
    """Escape characters that break Markdown formatting."""
    for ch in ("\\", "`", "*", "_", "{", "}", "[", "]", "|"):
        text = text.replace(ch, "\\" + ch)
    return text


def _format_dt(dt: datetime | None) -> str:
    if dt is None:
        return "unknown"
    return dt.strftime("%Y-%m-%d %H:%M UTC")


# ---------------------------------------------------------------------------
# Public renderer
# ---------------------------------------------------------------------------


def render_markdown(briefing: "Briefing") -> str:
    """
    Render a Briefing object to GitHub-Flavored Markdown.

    Parameters
    ----------
    briefing:
        The complete Briefing to render.

    Returns
    -------
    str
        GFM-formatted string ready to write to a .md file.
    """
    lines: list[str] = []

    # ---- Header ----
    lines.append(f"# News Radar — {briefing.date}")
    lines.append("")
    lines.append(
        f"*{len(briefing.items)} curated stories · "
        f"Generated {_format_dt(briefing.generated_at)}*"
    )
    lines.append("")

    # ---- Executive Summary ----
    if briefing.executive_summary:
        lines.append("## Overview")
        lines.append("")
        # Wrap each paragraph in a blockquote for visual separation
        for para in briefing.executive_summary.split("\n\n"):
            para = para.strip()
            if para:
                lines.append(f"> {para}")
                lines.append(">")
        # Remove trailing >
        if lines[-1] == ">":
            lines.pop()
        lines.append("")

    # ---- Top Topics ----
    if briefing.top_topics:
        lines.append("## Top Topics")
        lines.append("")
        topic_badges = " ".join(f"`{t}`" for t in briefing.top_topics)
        lines.append(topic_badges)
        lines.append("")

    lines.append("---")
    lines.append("")

    # ---- Stories ----
    for rank, si in enumerate(briefing.items, 1):
        lines.extend(_render_item_md(rank, si))

    # ---- Footer ----
    lines.append("---")
    lines.append("")
    model = briefing.items[0].model_used if briefing.items else "n/a"
    lines.append(
        f"*Generated by [News Radar](https://github.com/Harshads-git/news-radar) "
        f"· {model} · {_format_dt(briefing.generated_at)}*"
    )
    lines.append("")

    return "\n".join(lines)


def _render_item_md(rank: int, si: "SummarizedItem") -> list[str]:
    """Render a single SummarizedItem as Markdown lines."""
    lines: list[str] = []
    item = si.scored.item
    score = si.scored.ai_score
    headline = si.ai_headline or item.title

    # ---- Story header ----
    lines.append(f"## {rank}. {_md_escape(headline)}")
    lines.append("")

    # ---- Meta row ----
    score_str = _score_badge(score)
    published = _format_dt(item.published_at)
    meta_parts = [
        f"**Score:** {score_str}",
        f"**Source:** {_md_escape(item.source_name)}",
        f"**Published:** {published}",
    ]
    lines.append(" | ".join(meta_parts))
    lines.append("")

    # ---- Links row ----
    link_parts = [f"**[Read the full article →]({item.url})**"]
    if item.comments_url and item.comments_url != item.url:
        comment_label = f"💬 {item.comment_count or '?'} comments"
        link_parts.append(f"[{comment_label}]({item.comments_url})")
    lines.append(" | ".join(link_parts))
    lines.append("")

    # ---- AI Summary ----
    if si.ai_summary:
        lines.append("### Summary")
        lines.append("")
        for para in si.ai_summary.split("\n\n"):
            para = para.strip()
            if para:
                lines.append(para)
                lines.append("")

    # ---- Key Points ----
    if si.key_points:
        lines.append("### Key Points")
        lines.append("")
        for kp in si.key_points:
            lines.append(f"- {kp}")
        lines.append("")

    # ---- AI Reason (collapsed details) ----
    if si.scored.ai_reason:
        lines.append(
            "<details><summary>Why this score?</summary>"
            f"\n\n{_md_escape(si.scored.ai_reason)}\n\n</details>"
        )
        lines.append("")

    lines.append("---")
    lines.append("")

    return lines
